safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000
name:        Uamuzi Bora
description: Making HIV care awesome


source:      .
destination: ./_site
plugins:     ./_plugins
includes:    ./_includes
permalink:   /blog/archives/:year/:title

future:      true
lsi:         false
pygments:    false
markdown:    maruku

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

