baseurl:     /
url:         https://uamuzibora.org
name:        Uamuzi Bora
description: We are a UK charity who use mobile information technology and an electronic medical record to improve public health and primary care in Kenya.


source:      .
destination: ./_site
plugins:     ./_plugins
includes:    ./_includes
permalink:   /blog/articles/:year/:title
paginate: 20
paginate_path: /blog/:num

future:      true
lsi:         false
pygments:    false
markdown:    kramdown

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    assets/img/latex
  png_url:    /assets/img/latex

flickr_set:
  gallery_tag:   'p'
  gallery_class: 'gallery'
  a_href:        nil
  a_target:      '_blank'
  image_rel:     ''
  image_size:    's'
  api_key:       'd4c545fcedfbd389f48ee57ae335257c'